%%compare diets
dietscripts={'vegeterian.csv';'vegan.csv';'ideal.csv';...
    'european_avg.csv';'gluten_free.csv';'high_fiber.csv';...
    'mediterranean.csv'; ...
    'unhealthy.csv'; ...
    'highfat_lowcarb.csv'; ...
    'diabetes.csv'; ...
    'high_protein.csv'};
results=zeros(11,1);
for i=1:11
    char(dietscripts{i})
    diet_added=addDiet(merged,string(dietscripts{i}));
    grrate=optimizeCbModel(diet_added,'max');
    results(i)=grrate.f;
end